/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database_resources.MySQL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabão
 */
public class Frame_Select_Distinct_Module extends javax.swing.JFrame {
    //Developer variable declaration
    String part_code;
    //End varaible declaration
    
    /**
     * Creates new form Frame_Select_Distinct_Module
     */
    public Frame_Select_Distinct_Module(String part) {
        part_code = part;
        initComponents();
        this._addCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_text_alert_title = new javax.swing.JLabel();
        jLabel_text_selection_instructions = new javax.swing.JLabel();
        jComboBox_module_selection = new javax.swing.JComboBox();
        jLabel_button_confirm_selection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 22, 122));

        jLabel_text_alert_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_text_alert_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_text_alert_title.setText("O código lido existe em mais de um módulo!");

        jLabel_text_selection_instructions.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel_text_selection_instructions.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_text_selection_instructions.setText("Selecione o módulo que conterá a peça escaneada");

        jComboBox_module_selection.setBackground(new java.awt.Color(96, 59, 169));
        jComboBox_module_selection.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_module_selection.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_button_confirm_selection.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_button_confirm_selection.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_button_confirm_selection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_button_confirm_selection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8_checkmark_50px.png"))); // NOI18N
        jLabel_button_confirm_selection.setText("  Confirmar");
        jLabel_button_confirm_selection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_button_confirm_selectionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_text_selection_instructions)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_text_alert_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_module_selection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_button_confirm_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel_text_alert_title)
                .addGap(48, 48, 48)
                .addComponent(jLabel_text_selection_instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_module_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel_button_confirm_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_button_confirm_selectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_button_confirm_selectionMouseClicked
        try{
            MySQL database = new MySQL();
            Statement st = database.getConect().createStatement();
            
            String query_SQL = ("SELECT * FROM `formasete`.`scannerpecas` WHERE (`codigopeca` = '" + part_code + "' and `codigomodulo` = '" + _get_module_code()+ "');");
            st.executeQuery(query_SQL);
            ResultSet linhaSQL = st.getResultSet();
            linhaSQL.first();
            int unidadeslidas = linhaSQL.getInt("unidadeslidas");
            unidadeslidas = unidadeslidas + 1;
            
            query_SQL = ("UPDATE `formasete`.`scannerpecas` SET `unidadeslidas` = '" + unidadeslidas + "' WHERE (`codigopeca` = '" + part_code + "' and `codigomodulo` = '" + _get_module_code()+ "');");
            st.executeUpdate(query_SQL);
            
            database.getConect().close();
            
            Frame_Scanning_Monitor window = new Frame_Scanning_Monitor();
            window.setLocationRelativeTo(null);
            window.setVisible(true);
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        JOptionPane.showMessageDialog(null, "Peça escaneada com sucesso!");
        
        this.dispose();
    }//GEN-LAST:event_jLabel_button_confirm_selectionMouseClicked

    public int _getItemCount(){
        return(jComboBox_module_selection.getItemCount());
    }
    
    public String _get_module_code(){
        int i=0;
        String codigomodulo;
        if(jComboBox_module_selection.getSelectedItem().toString().contains("-")){
            while(jComboBox_module_selection.getSelectedItem().toString().charAt(i) != '-'){
                i++;
            }
            codigomodulo = jComboBox_module_selection.getSelectedItem().toString().substring(0, i);
        }else{
            codigomodulo = jComboBox_module_selection.getSelectedItem().toString();
        }
        return(codigomodulo);
    }

    private void _addCombobox(){
        try{
            MySQL database = new MySQL();
            Statement st = database.getConect().createStatement();
            
            String query_SQL = ("SELECT * FROM `formasete`.`scannerpecas` WHERE codigopeca = '" + part_code + "' and unidades != unidadeslidas;");
            st.executeQuery(query_SQL);
            ResultSet linhaSQL = st.getResultSet();
            
            while(linhaSQL.next()){
                if(!(linhaSQL.getString("descricaomodulo").equals(""))){
                    jComboBox_module_selection.addItem(linhaSQL.getString("codigomodulo") + " - " + linhaSQL.getString("descricaomodulo"));
                }else{
                    jComboBox_module_selection.addItem(linhaSQL.getString("codigomodulo"));
                }
            }
            
        database.getConect().close();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_module_selection;
    private javax.swing.JLabel jLabel_button_confirm_selection;
    private javax.swing.JLabel jLabel_text_alert_title;
    private javax.swing.JLabel jLabel_text_selection_instructions;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
