/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabão
 */
public class Frame_Verified extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Verified
     */
    public Frame_Verified() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_logo_verified = new javax.swing.JLabel();
        jLabel1_button_back_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 83, 121));

        jLabel_logo_verified.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormaSete_resized_verified.png"))); // NOI18N

        jLabel1_button_back_menu.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1_button_back_menu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_button_back_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_button_back_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8_double_left_50px.png"))); // NOI18N
        jLabel1_button_back_menu.setText("  Voltar ao Menu");
        jLabel1_button_back_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_button_back_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_logo_verified, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1_button_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_logo_verified)
                .addGap(18, 18, 18)
                .addComponent(jLabel1_button_back_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1_button_back_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_button_back_menuMouseClicked
        Frame_Menu window = new Frame_Menu();
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1_button_back_menuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_button_back_menu;
    private javax.swing.JLabel jLabel_logo_verified;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
