/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.pdfbox.text.PDFTextStripperByArea;
import database_resources.MySQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import model.Data_Model;
import model.PDF_Promob_Report_Handler;

/**
 *
 * @author Gabão
 */
public class Frame_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Menu
     */
    public Frame_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_img_logo = new javax.swing.JLabel();
        jLabel_button_load_new_PDF = new javax.swing.JLabel();
        jLabel_button_resume_last_scanning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(22, 63, 79));

        jLabel_img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormaSete_logo.png"))); // NOI18N

        jLabel_button_load_new_PDF.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel_button_load_new_PDF.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_button_load_new_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8_software_installer_50px.png"))); // NOI18N
        jLabel_button_load_new_PDF.setText("   Carregar PDF Novo");
        jLabel_button_load_new_PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_button_load_new_PDFMouseClicked(evt);
            }
        });

        jLabel_button_resume_last_scanning.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel_button_resume_last_scanning.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_button_resume_last_scanning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8_rollback_50px.png"))); // NOI18N
        jLabel_button_resume_last_scanning.setText("   Retomar Último Escaneamento");
        jLabel_button_resume_last_scanning.setToolTipText("");
        jLabel_button_resume_last_scanning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_button_resume_last_scanningMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_img_logo)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_button_resume_last_scanning)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_button_load_new_PDF)
                        .addGap(265, 265, 265))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_img_logo)
                .addGap(162, 162, 162)
                .addComponent(jLabel_button_load_new_PDF)
                .addGap(72, 72, 72)
                .addComponent(jLabel_button_resume_last_scanning)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void _remove_all_data_database(){
        try{
            MySQL database = new MySQL();
            Statement st = database.getConect().createStatement();
            String query_SQL = ("TRUNCATE TABLE scannerpecas;");
            st.executeUpdate(query_SQL);
            database.getConect().close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void _add_row_database(String descmod, String codigomod, String descpec, String codigopec, String un, String uns){
        try{
            MySQL database = new MySQL();
            Statement st = database.getConect().createStatement();
            String query_SQL = ("INSERT INTO `formasete`.`scannerpecas` (`descricaomodulo`, `codigomodulo`, `descricaopeca`, `codigopeca`, `unidades`, `unidadeslidas`) VALUES ('" + descmod + "', '" + codigomod + "', '" + descpec + "', '" + codigopec + "', '" + un + "', '" + uns + "')");
            st.executeUpdate(query_SQL);
            database.getConect().close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void _extract_pdf_data(String pdf_file_path){
        try (PDDocument document = PDDocument.load(new File(pdf_file_path))) {
            document.getClass();
            if (!document.isEncrypted()) {
                
                PDFTextStripperByArea stripper = new PDFTextStripperByArea();
                stripper.setSortByPosition(true);

                PDFTextStripper tStripper = new PDFTextStripper();

                String pdfFileInText = tStripper.getText(document);
                //System.out.println("Text:" + st);

				// split by whitespace
                String lines[] = pdfFileInText.split("\\r?\\n");
                
                PDF_Promob_Report_Handler extractor = new PDF_Promob_Report_Handler();
                Data_Model data = new Data_Model();
                int index = 0;

                while(lines.length > index){
                    data.setModule_code(extractor.get_module_code(index, lines));
                    data.setModule_description(extractor.get_module_description(index, lines));
                    index += 2;
                    while(!(lines[index].contains("Empresa")) && !(lines[index].contains("-"))){
                        data.setPart_code(extractor.get_part_code(index, lines));
                        data.setPart_description(extractor.get_part_description(index, lines));
                        while(!(lines[index].contains("UN")) && !(lines[index].contains("M2")) && !(lines[index].contains("M"))){
                            index++;
                        }                            
                        data.setPart_units(extractor.get_part_units(index, lines));
                        this._add_row_database(data.getModule_description(), data.getModule_code(), data.getPart_description(), data.getPart_code(), Integer.toString(data.getPart_units()), "0");
                        index++;
                    }
                    if(lines[index].contains("Empresa")){
                        index+=5;
                    }
                }
            }
        }catch(IOException e){
            
        }
    }
    
    private void jLabel_button_load_new_PDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_button_load_new_PDFMouseClicked
        JFileChooser archive_path = new JFileChooser();
        FileNameExtensionFilter archive_filter = new FileNameExtensionFilter("Arquivo PDF", "pdf");
        archive_path.addChoosableFileFilter(archive_filter);
        archive_path.setAcceptAllFileFilterUsed(false);
        archive_path.setMultiSelectionEnabled(false);
        
        if(archive_path.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            this._remove_all_data_database();
            this._extract_pdf_data(archive_path.getSelectedFile().getAbsolutePath());
            //this._load_all_data_database();
            
            Frame_Scanning_Monitor window = new Frame_Scanning_Monitor();
            window.setLocationRelativeTo(null);
            window.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel_button_load_new_PDFMouseClicked

    private void jLabel_button_resume_last_scanningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_button_resume_last_scanningMouseClicked
        try{
            MySQL database = new MySQL();
            Statement st = database.getConect().createStatement();
            String query_SQL = ("SELECT * FROM `formasete`.`scannerpecas`");
            st.executeQuery(query_SQL);
            ResultSet linhaSQL = st.getResultSet();
            
            int i = 0;
            while(linhaSQL.next()){
                i++;
            }
            
            if(i>0){
                Frame_Scanning_Monitor janela = new Frame_Scanning_Monitor();
                janela.setVisible(true);
                janela.setLocationRelativeTo(null);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "A última verificação foi terminada com êxito! Inicie uma nova para escanear as peças.");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLabel_button_resume_last_scanningMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_button_load_new_PDF;
    private javax.swing.JLabel jLabel_button_resume_last_scanning;
    private javax.swing.JLabel jLabel_img_logo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    // Dev variables declaration
    Vector conteudo_arq = new Vector();
    // End of dev variables declaration
    
}
